name: ubuntu
on: [push]
jobs:
  build:
    name: build with meson
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
        
      
      
